### PR TITLE
Added specs for requirejs amd loading

### PR DESCRIPTION
**Pull request by thegillis**
I wasn't aware there was already a fix in master for loading i18n.js file over requirejs. Since the fix is already applied, here is the test I used to verify the bug: spec/js/specs_requirejs.html

It only requires a small change to the translations javascript file to detect amd loading.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Can this also be auto run?
Just curious, not a blocker.

**Comment by PikachuEXE** [comment]
The spec seems to fail since `I18n` is always undefined

**Comment by thegillis** [comment]
Alright, I clearly have a commit problem. Let me double check what I have and see if I can get those tests to pass.

**Comment by thegillis** [comment]
Alright, should all pass now.

I wrote the tests not knowing the missing "return" bug in rc8 was already fixed in master. My fix did not explicitly name the module 'i18n' in the define call:

https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L21

I added a mapping to fix the module loading.

I have not yet looked at how auto running the js specs work.

**Comment by PikachuEXE** [comment]
All seems fine now :)

**Comment by PikachuEXE** [comment]
I am going to study how to run it from command line

**Pull request merged**
