### PR TITLE
Bugfix: make i18n-js compatible with rails 5

### PR DESCRIPTION
**Pull request by AubinWinddle**
I, this is a little fix to the open issue #404 to be able to use I18n-js with Rails 5 and asset pipeline. I think it will be more interesting to merge rails4 and rails5 methods since it's the same behavior. To discuss.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
CI failed but should be related to Ruby vs rails version conflict since rails 5 requires Ruby 2.2.2+
Merging

**Comment by guguso** [comment]
@pikachuExe could you please release a v3.0.0.rc14 version to make this fix available ?
Thks

**Comment by PikachuEXE** [comment]
I will do it this week (today/tomorrow)
Sorry I planned to do it last Friday but was too busy

**Comment by PikachuEXE** [comment]
Just released 3.0.0.rc14

**Comment by guguso** [comment]
@PikachuEXE thks a lot

**Comment by fwininger** [comment]
@PikachuEXE thanks !

**Comment by SzNagyMisu** [comment]
@PikachuEXE would it be possible to update the _Installation_ part of the README file? I had the same issue, took me two hours to find that 3.0.0.rc11 is not the latest version. Thanks! And thanks for fixing the problem :-) !

**Comment by PikachuEXE** [comment]
`gem "i18n-js", ">= 3.0.0.rc11"` should already make you install latest RC version
Unless it's already locked

**Comment by SzNagyMisu** [comment]
I see. Then I'm not sure what really solved my problem. It seemed to me that it was the change from rc11 to rc15 which is the current latest according to [rubygems.org](https://rubygems.org/gems/i18n-js/versions). Thanks anyway.

**Comment by fwininger** [comment]
I don't thinks that is the good place to open a thread to release version issue.

But to solve definitively this issue, could you use standard release number, like 3.0.15 and not 3.0.0.rc5. 

So everyone can use gem install i18-js or gem 'i18n-js'.

**Comment by PikachuEXE** [comment]
Let's discuss further about version in another issue or gitter channel
https://gitter.im/fnando/i18n-js

**Pull request merged**
