### PR TITLE
fix fallback bug

### PR DESCRIPTION
**Pull request by kilolumen**
Fix #465  #460

### CODE REVIEW

**Comment by PikachuEXE** [comment]
What does it archive?
I already added [some test cases in #465](https://github.com/fnando/i18n-js/pull/465/files#diff-f457053fa319b8c5770938ef83d666bc)

**Comment by kilolumen** [comment]
old: locales = ["zh-Hans-tw", "zh", "zh-Hans", "en"]
fix:  locales = ["zh-Hans-tw", "zh-Hans", "zh", "en"]
i18n.js line: 400
```while (locales.length) {
        locale = locales.shift();
        scopes = fullScope.split(this.defaultSeparator);
        translations = this.translations[locale];
        // ....
     }
```

**Comment by PikachuEXE** [comment]
OK Please add a test case to ensure this fix is working

**Comment by kilolumen** [comment]
I already added a test case.

**Comment by PikachuEXE** [comment]
Thanks, will release soon

**Comment by PikachuEXE** [comment]
`3.0.2` released (gem + npm)

**Pull request merged**
