### PR TITLE
2.x - Fix permission of i18njs-cache

### PR DESCRIPTION
**Pull request by bpourriahi**
Please fix. This is breaking our dev environment and deployments.

Thanks.

### CODE REVIEW

**Comment by jesperronn** [comment]
Hi, can you provide a desciption of the error. I think I have an error in my app (recently added translations missing), but I am uncertain if this can fix it.

**Comment by jesperronn** [comment]
Also, why is Travis failing the build? It states 

``` 
rake aborted!
Don't know how to build task 'default'
```

Can you restart the build, or – if it's easier – make an empty commit

**Comment by PikachuEXE** [comment]
Can you rebase on 2.x now?
I have fixed the spec (at least the build passed)

**Comment by jesperronn** [comment]
I same failure from Travis linked here on the github page. Same problem as before, 'rake no default task'

* https://travis-ci.org/fnando/i18n-js/builds/37231142

(ran 4 hours ago)

@fnando if this is problem is unrelated to the fix, then maybe you can fix Travis?.

**Comment by PikachuEXE** [comment]
You need to rebase on the `2.x` branch, since that fixed travis build
See https://travis-ci.org/fnando/i18n-js/builds/54190406

**Comment by PikachuEXE** [comment]
It's almost a year, please rebase or I will close this PR since it's stale

**Pull request closed without merging**
