### PR TITLE
Support :exclude as an alias for :except

### PR DESCRIPTION
**Pull request by johnnyshields**
Rails uses the terminology `:only` and `:exclude`. It was a bit unnatural when I found this was called `:except`

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I think I will look at this after config refactor :S
But this is valid

Might as well rename the whole option z_z

**Comment by johnnyshields** [comment]
Why not merge this as-is? I think there's no problem supporting both names.

**Comment by PikachuEXE** [comment]
Having "aliases" creates need for extra testing.
If this is a "rename option" PR, I can accept it before the refactor.

**Comment by PikachuEXE** [comment]
@johnnyshields 
Do you still want this?
If so please update rebase and let me know

**Comment by PikachuEXE** [comment]
Oh please update README too

**Comment by johnnyshields** [comment]
@PikachuEXE please merge

**Comment by johnnyshields** [comment]
You're right, I think it's better to keep only and except. I will close this PR it's not needed

**Pull request closed without merging**
