### PR TITLE
Allow scoped calls to toHumanSize()

### PR DESCRIPTION
**Pull request by scumah**
Hey! This PR adds support for the `scope` option to the `toHumanSize()` function.

Right now, the function directly looks for a specific hardcoded scope that doesn't take into account if the user is passing a `scope` option. In our case, we wanted to have this kind of translations under a `shared` scope, along the date formats and that kind of stuff, but using `toHumanSize()` in it's current state makes it impossible.

To fix it we calculate the scope before calling `t()` using `getFullScope()`, passing the options `toHumanSize()` got.

Thanks!

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Sorry I am on holiday
Come back next week

**Comment by PikachuEXE** [comment]
That seems a great addition
Can you also update the README to reflect your changes?

**Comment by scumah** [comment]
Done @PikachuEXE. I took the chance and:
- Fixed a couple of typos
- Updated the plural rules broken link
- Removed trailing white spaces

**Comment by PikachuEXE** [comment]
Hey thx
But I notice some trailing double spaces are removed which is for formatting
Can you add back those double spaces to keep the formatting right? (Unless that's also part of the fix)

**Comment by scumah** [comment]
wops! I didn't know about this double space for md, sry. fixing it!

**Pull request merged**
