### PR TITLE
RequireJS optimization doesn't correctly detect define method in i18n.js

### PR DESCRIPTION
**Pull request by thegillis**
Example fix for bug #314.

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Can you run test added in #311?
I can't get auto test for require JS working yet :S

**Comment by thegillis** [comment]
Both the spec.html file and spec_requirejs.html file run without errors:

spec.html:
i18n_spec

spec_requirejs.html
i18n_requirejs

**Comment by PikachuEXE** [comment]
Really need some automatic test for this kind of stuff Q_Q

**Comment by PikachuEXE** [comment]
@thegillis 
Off topic
Can you give a try on #446 ?
I fixed the case for browser global but not sure if I break AMD/CommonJS case

**Comment by PikachuEXE** [comment]
I am gonna assume it's working fine

**Pull request merged**
