### PR TITLE
Backport #376 to 2.x

### PR DESCRIPTION
**Pull request by yuku-t**
Ref #376

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I think there are other stuff needs to be done before this can be backported
But I only understand & support 3.x :S

**Comment by yuku-t** [comment]
It seems that an error occurred while installing bundled gems, not while testing.

> But I only understand & support 3.x :S

okay, please feel free to close this PR :expressionless:

**Comment by PikachuEXE** [comment]
@yuku-t 
If you can summon the original author... :joy:

**Comment by yuku-t** [comment]
the original author escaped...? :fearful: 
I'll apply the patch by myself until 3.0.0 is out. Look forward to the next release :+1:

**Comment by PikachuEXE** [comment]
Well he is active in his other projects but I guess he ignores this project now (after adding me)

**Pull request closed without merging**
