### PR TITLE
json_only option should allow multiple locales in one file

### PR DESCRIPTION
**Pull request by johnnyshields**
- `json_only` option should allow multiple locales.
- Refactor segment writer code to use formatter classes. This can be extended in the future if needed to support other formats easily.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@PikachuEXE please merge

**Comment by johnnyshields** [comment]
@PikachuEXE please merge

**Comment by johnnyshields** [comment]
@PikachuEXE please merge

**Comment by PikachuEXE** [comment]
Released in `3.2.1`

**Pull request merged**
