### PR TITLE
use immutable options when doing lookup

### PR DESCRIPTION
**Pull request by astephenb**
Fixes issue where defaultValue option provided but not used in lookup
because of mutation in `createTranslationOptions`

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Got merge conflict probably due to #450 merged
I am not sure if this PR is relevant anymore

Also if still relevant please add a test case

**Comment by PikachuEXE** [comment]
Will the conflict be resolved?

**Comment by PikachuEXE** [comment]
@astephenb 
Hello again.
Will the conflict be resolved?

**Comment by PikachuEXE** [comment]
Also please provide test case

**Comment by astephenb** [comment]
Sorry @PikachuEXE I have been traveling... I will look at this again today.

**Comment by astephenb** [comment]
@PikachuEXE looks like this was fixed in 1c85c04b618f7b5570b2c0a5ddba3a1b89275d16. I'll close. Thanks for following up.

**Pull request closed without merging**
