### PR TITLE
Fix for #350 middleware caching

### PR DESCRIPTION
**Pull request by tleish**
clear middleware cache each time rails restarts and calls middleware is initialized which will resolve issue #350

### CODE REVIEW

**Comment by PikachuEXE** [comment]
This is the same as removing the caching in middleware
Is that what you intended to do?

**Comment by PikachuEXE** [comment]
Can you add a change log entry?

**Comment by tleish** [comment]
Added entry to changelog

**Comment by PikachuEXE** [comment]
Thanks :D

**Pull request merged**
